docker:
  image: "yegor256/java8"
env:
  USER: "Zoltan"
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}" -e -X
    git commit -am "${tag}"
    mvn clean -DskipTests deploy -Dfile.encoding=UTF-8 -Pfoo -Psonatype --settings /home/r/settings.xml -e -X
