env:
  USER: "Zoltan"
docker:
  image: "mostalive/ubuntu-14.04-oracle-jdk8"
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean -DskipTests deploy -Pfoo -Psonatype --settings /home/r/settings.xml
