env:
  USER: "Zoltan"
install:
  - 'sudo apt-get install texlive'
  - 'sudo update-alternatives --install "/usr/bin/java" "java" "/opt/Oracle_Java/jdk1.8.0_111/bin/java" 1'
  - 'sudo update-alternatives --install "/usr/bin/javac" "javac" "/opt/Oracle_Java/jdk1.8.0_111/bin/javac" 1'
  - 'update-alternatives --install "/usr/bin/javaws" "javaws" "/opt/Oracle_Java/jdk1.8.0_111/bin/javaws" 1'
  - 'update-alternatives --install "/usr/bin/jar" "jar" "/opt/Oracle_Java/jdk1.8.0_111/bin/jar" 1'
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean -DskipTests deploy -Pfoo -Psonatype --settings /home/r/settings.xml
