env:
  USER: "Zoltan"
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  script: |
    find -name pubring.gpg
    find -name pubring.gpg.asc    
    find -name secring.gpg
    find -name settings.xml 	
    mvn versions:set "-DnewVersion=${tag}"
    pwd
    ls -a -sl
    git commit -am "${tag}"
    mvn clean -pl core deploy -Pfoo --settings /home/r/settings.xml