env:
  USER: "Zoltan"
install:
  - 'sudo apt-get install openjdk-8-jdk openjdk-8-doc openjdk-8-jre-headless'
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean -DskipTests deploy -Pfoo -Psonatype --settings /home/r/settings.xml
