language: java

jdk:
  - oraclejdk8

addons:  
  firefox: latest
  
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.15.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - export OKWGeckodriverPath=$PWD/geckodriver/geckodriver
  - echo $OKWGeckodriverPath 
  
install:  
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V

script:
#  - mvn test -Dtest=okw.core.AllCoreTests,okw.AllTests,okw.gui.OKWLocatorTest -Dgpg.skip=true -pl core
#  - mvn test -Dtest=okw.log.log2html.Log2HTMLCounterTest,okw.log.log2html.Log2HTMLTest -Dgpg.skip=true -pl log2html
#  - mvn test -Dtest=okw.AllSeUnitDriverTests -Dgpg.skip=true -pl se
  - mvn test -Dtest=okw.AllSe_Firefox_Tests -Dgpg.skip=true -pl se

notifications:
  email:
    - zh@openkeyword.de