language: java
# dist: xenial

# This will run on Travis' 'new' container-based infrastructure
# sudo: false

# Blacklist
branches:
  except:
    - gh-pages
    
jdk:
  - openjdk8

addons:  
  chrome: stable
  apt:
    packages:
      - texlive-latex-base
      - perl
      - graphviz

# Environment variables
env:
  global:
    - GH_REPO_NAME: OKW
    - DOXYFILE: $TRAVIS_BUILD_DIR/src/doxygen/OKW_DE.doxyfile
    - GH_REPO_REF: github.com/Hrabovszki1023/OKW.git
    - WORKSPACE: $TRAVIS_BUILD_DIR
    - BUILD_ID: $TRAVIS_BUILD_NUMBER
    - BUILD_TIMESTAMP_DE: $(date +"%m.%d.%Y %T")
    - OKWChromedriverPath: "/usr/local/bin/chromedriver"
  matrix:
    - TESTCASE="okw.gui.OKWLocatorTest"
      Package="core"
#    - TESTCASE="okw.core.AllCoreTests"
#      Package="core"
    - TESTCASE="okw.AllTests"
      Package="core"
    - TESTCASE="okw.log.log2html.Log2HTMLCounterTest"
      Package="log2html"
    - TESTCASE="okw.log.log2html.Log2HTMLTest"
      Package="log2html"
    - TESTCASE="okw.SeButton.SeButton_EN_Chrome_Test"
      Package="se"
    
      
# before_install:
  
install: 
  # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
  - wget -N http://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver $OKWChromedriverPath
#
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  
script:
  # 
  - mvn test -Dtest=$TESTCASE -Dgpg.skip=true -pl $Package

# Generate and deploy documentation
jobs:
  include:
    - stage: doxygen
      script: ls
      after_success:
        - cd $TRAVIS_BUILD_DIR
        - chmod +x InstallDoxygen.sh
        - ./InstallDoxygen.sh
        - chmod +x generateDocumentationAndDeploy.sh
        - ./generateDocumentationAndDeploy.sh
        - cd $TRAVIS_BUILD_DIR/html

notifications:
  email:
    - zh@openkeyword.de
