@startuml OKW_State.svg
 [*] --> OK : Execute Test
 OK --> NOK : OKW_Exception
 NOK --> OK: BeginTest
 OK --> OK: OKW-Keyword
 OK --> [*]
 NOK --> [*]
@enduml
@startuml OKW_StateClass.svg
 class Core
 interface IOKW_State
 class OK
 class NOK
  
 Core o-- IOKW_State: CurrentState
 OK --> Core: core
 NOK --> Core: core
 IOKW_State <|.. OK
 IOKW_State <|.. NOK
@enduml
@startuml OKW_UseCase_Keyword_de.svg
:Fachtester: -right-> (Testfall in Schlüsselwortnotation) : erstellt
@enduml
@startuml inline_umlgraph_1.svg
  class SeInputRadio [[java:okw.gui.adapter.selenium.SeInputRadio]] {
  ..Constructor..
  +SeInputRadio(String Locator, OKWLocator[] Locators)
  +SeInputRadio(String IframeID, String Locator, OKWLocator[] Locators)
  ..Getter/Setter..
  +ArrayList<String> getValue()
  +Boolean getIsSelected()
  +ArrayList<String> getCaption()
  +void SetValue(ArrayList<String> Values)
  +Boolean getHasFocus()
  .. Keyword API..
  +void SetFocus()
  +void TypeKey(ArrayList<String> fps_Values)
  }
class SeAnyChildWindow [[java:okw.gui.adapter.selenium.SeAnyChildWindow]] {
  }
SeAnyChildWindow <|-- SeInputRadio
@enduml
@startuml SeLinkExtendsSeAnyChildWindow.svg
 class SeLink [[java:okw.gui.adapter.selenium.SeLink]]{
    +SeLink(String Locator, OKWLocator[] Locators)
    +SeLink(String IframeID, String Locator, OKWLocator[] Locators)
    ..Simple Getters..
    +Boolean getIsActive()
    +ArrayList<String> getValue()
    ..Keyword API..
    +void TypeKey(ArrayList<String> fps_Values)
    }
    
 class SeAnyChildWindow [[java:okw.gui.adapter.selenium.SeAnyChildWindow]]{
 }
 SeAnyChildWindow <|-- SeLink
@enduml
@startuml inline_umlgraph_2.svg
participant "Handle Exception"
participant getValue
participant WaitForMe
participant getAttribute
->getValue: Call from "Value"-Keyword
activate getValue
getValue -> WaitForMe
WaitForMe -> "Handle Exception": OKWGUIObjectNotFoundException

getValue -> getAttribute: getAttribute "href"
activate getAttribute
getAttribute -> : read "href" via Selenium
getAttribute <- : return Value("href")
getAttribute -> getValue: return Value("href")
deactivate getAttribute

<- getValue: return Value("href")
deactivate getValue
@enduml
@startuml inline_umlgraph_3.svg
class SeRadioList [[java:okw.gui.adapter.selenium.SeRadioList]] {
    ~OKW_CurrentObject_Sngltn CO
    ~FrameObjectDictionary_Sngltn FOD
    ~ArrayList<String> myRadioButtonFNs
  ..Constructor..
    +SeRadioList(String Locator, OKWLocator[] Locators)
    +SeRadioList(String IframeID, String Locator, OKWLocator[] Locators)
  .. Getter/Setter..
    +ArrayList<String> getValue()
    +ArrayList<String> getLabel()
  .. Keyword API..
    +void SetValue(ArrayList<String> Val)
    +void Select(ArrayList<String> Val)
}
class SeAnyChildWindow [[java:okw.gui.adapter.selenium.SeAnyChildWindow]] {
}
SeAnyChildWindow <|-- SeRadioList
@enduml
@startuml inline_umlgraph_4.svg
 class SeSelect [[java:okw.gui.adapter.selenium.SeSelect]] {
  ..Constructor..
 +SeSelect(String Locator, OKWLocator[] Locators)
  .. Keyword API..
  +void Select(ArrayList<String> fps_Values)
  +void SetValue(ArrayList<String> fpsValues)
  +ArrayList<String> getValue()
}
class SeAnyChildWindow [[java:okw.gui.adapter.selenium.SeAnyChildWindow]] {
}
SeAnyChildWindow <|-- SeSelect
@enduml
